name: daily
on:
  push:
  schedule:
  - cron: '6 0 * * *'  # M H d m w (daily at 00:06)
jobs:
  ghstat:
    if: github.event_name != 'pull_request' || !contains('OWNER,MEMBER,COLLABORATOR', github.event.pull_request.author_association)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with: {python-version: '3.x'}
    - uses: actions/checkout@v4
    - uses: ./
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        gist-id: ${{ secrets.GIST_ID }}
        # author: Casper da Costa-Luis
        # user: casperdcl
        repos-incl: ${{ secrets.REPOS_INCL }}
        repos-skip: ${{ secrets.REPOS_SKIP }}
        lang-names: ${{ secrets.LANG_NAMES }}
